### ISSUE TITLE
Outdated Cocoa Pod

### ISSUE THREAD

**Issue by abduranjum** [aryaxt/OCMapper#13]
The Cocoa Pod is outdated. Kindly update it. Thanks.

**Comment by aryaxt** [comment]
The latest version with Swift compatibility won't work as a pod YET, because swift uses the module as a part of class names, and therefore OCMapper must be in the same module as the models object are.

Haven't figured out a clean way to handle this yet

**Comment by abduranjum** [comment]
Thanks for the quick reply!

Okay, fine. Your OCMapper is really helping us!

Assalamualaikum,

Jazakallah
--
Regards,
Abdurrahman Mubeen Ali
0092-321-486-2986
iOS Software Engineer
Technosoft Solutions Inc.
<abdur.anjum@gmail.com>

**Comment by aryaxt** [comment]
Version 1.5 is now available in cocoapods
