### ISSUE TITLE
How to use InCodeMappingProvider with swift

### ISSUE THREAD

**Issue by hopiaw** [aryaxt/OCMapper#16]
Hi,

I'm not sure this question is relevant but how do you use:

- (void)mapFromDictionaryKey:(NSString *)dictionaryKey toPropertyKey:(NSString *)propertyKey forClass:(Class)class withTransformer:(MappingTransformer)transformer;

in swift?

I always got the following error: Argument withTransformer must precede argument forClass.

Could you post an example of this method used in Swift please.

Thanks.

**Comment by aryaxt** [comment]
mappingProvider.mapFromDictionaryKey("description", toPropertyKey:"fullDescription", forClass:User..self)

**Comment by hopiaw** [comment]
Yes but what about the value for the parameter withTransformer? I'm using a closure but it does not works. Thanks for the help.

**Comment by aryaxt** [comment]
Oops overlooked it. Don't have swift setup so gonna take a guess.
Let me know if it doesn't work I'll setup swift and find out why it's not working.

```Swift
mappingProvider.mapFromDictionaryKey("description", toPropertyKey:"fullDescription", forClass:User..self) { node, parent in {
   return "Something"
}
```

**Comment by hopiaw** [comment]
Humm... this works but when using directly the parameter withTransformer, I'm not able to make it work. Weird.

The first 2 examples work, but not the third one. The one I was using of course:


        inCodeMappingProvider.mapFromDictionaryKey("key",
            toPropertyKey: "property",
            forClass: PatientRecord.self){
                node, parent in
                return "Something"
            }
        
        inCodeMappingProvider.mapFromDictionaryKey("key",
            toPropertyKey: "property",
            forClass: PatientRecord.self,
            withTransformer:{ s1, s2 in return s1})
        
        inCodeMappingProvider.mapFromDictionaryKey("key",
            toPropertyKey: "property",
            forClass: PatientRecord.self,
            withTransformer: { (s1:AnyObject, s2:AnyObject) -> AnyObject
                return "Something"
        })

**Comment by hopiaw** [comment]
I always got the error: Argument withTransformer must precede argument forClass.
with the third example above. It might be due to the bridge between Objective C and Swift. Idk...

**Comment by aryaxt** [comment]
So do the first examples still not work?
 Last example is missing ```in```

**Comment by hopiaw** [comment]
First 2 are working, and yes I saw that in missing for the third one. Still not working.

**Comment by aryaxt** [comment]
That's odd. Maybe change AnyObject to Any?

**Comment by hopiaw** [comment]
I tried yes, nope.

**Comment by hopiaw** [comment]
Oh god! Of course...
The signature of MappingTransformer use id. So parameters in the closure must be optional. Now it works:

        inCodeMappingProvider.mapFromDictionaryKey("key",
            toPropertyKey: "property",
            forClass: PatientRecord.self,
            withTransformer: { (s1:AnyObject?, s2:AnyObject?) -> AnyObject in
                return "Something"
        })

Again, swift error was with a big help, haha!

Thanks again for your help.

**Comment by aryaxt** [comment]
cool, good catch. Hopefully Xcode 6.3 is gonna be more informative about errors :)

**Comment by Sajjon** [comment]
Hi! Just found this Github projects, it looks amazing! And I am thinking about replacing [JSONJoy](https://github.com/daltoniam/JSONJoy-Swift) with it, since JSONJoy does not automatically match JSON values to Model properties. 

Where can I put the inCodeMappingProvider.mapFromDictionaryKey code, when I want to use another name of my property than the JSON key? 

I am using Swift, Alamofire and the Alamofire.Request extension

Can I add code for "re-mapping" of property-JSONkey names inside the init for each model? 

Extremely thankful for any help!

Thanks! :)

**Comment by aryaxt** [comment]
@Sajjon Glad you found it helpful. I personally don't like adding parsing logic to models, I usually create a mapping manager file that has all my mapping, and I call it from appDelegate. Take a look at this class: https://github.com/aryaxt/OCMapper/blob/master/OCMapper/Sample/Service%20Layer/OCMapperConfig.m
