### ISSUE TITLE
class keyword causes issues withIn the subclassed objective-c class

### ISSUE THREAD

**Issue by jessepollak** [aryaxt/OCMapper#25]
I've been using OCMapper in Swift and I've run into a compilation problem. This may be an issue with XCode/Swift/Objective-C, but I figured I would open an issue here.

All was working well until I tried to subclass a custom Objective-C class that I had created (a subclass of `UIViewController`). When I tried to do this, I ran into a build error which pointed to OCMapper.

![screenshot 2015-05-20 11 58 55](https://cloud.githubusercontent.com/assets/1097953/7733964/9bd59c02-fee7-11e4-8d9c-7316b5861bbc.png)
![screenshot 2015-05-20 11 57 26](https://cloud.githubusercontent.com/assets/1097953/7733965/9bd7db20-fee7-11e4-8d25-325aa730fa7d.png)

Not subclassing the custom Objective-C class makes the build error go away (even if I still do the import).

Any ideas?

**Comment by aryaxt** [comment]
What do you mean by this "Not subclassing the custom Objective-C class makes the build error go away"?

I'm using it in Swift myself, and I have many subclasses of objective-c classes with no issue.
Does renaming the class parameter to something else fix the issue?

**Comment by jessepollak** [comment]
So, if I leave the import in my `Module-Bridging-Header.h` and instead of subclassing `CustomViewController`, I subclass `UIViewController`, the app builds. It's only when I subclass `CustomViewController` in my Swift code that the build fails.

Yes, I changed it to `klass` and the problem was resolved, but I'm using Cocoapods, so this isn't really viable.

Thank you so much for your help :)

**Comment by aryaxt** [comment]
That's really odd, will look into it and change that in the next version.

**Comment by jessepollak** [comment]
Thank you, I'm just holding out from subclassing in Swift for as long as possible :)

**Comment by aryaxt** [comment]
Just one more thing before I push a fix for this. Are you using Swift 1.2?

**Comment by jessepollak** [comment]
I have XCode 6.3.1, which comes with v1.2, so I'm pretty sure, yes.

**Comment by aryaxt** [comment]
Can you check if this commit fixes the issue for you?

pod 'OCMapper', :git => 'https://github.com/aryaxt/OCMapper.git', :commit => '8a26f84537b803c1502963cb4e238195213ec8b3'

**Comment by jessepollak** [comment]
This does indeed fix the issue — sorry about the delay!

**Comment by aryaxt** [comment]
Cool, will push this to cocoapods tonight

**Comment by jessepollak** [comment]
Awesome, thank you!

**Comment by edwardvalentini** [comment]
+1 i have the same issue :)
