### ISSUE TITLE
ObjectMapper. Use sharedInstance vs create new instance.

### ISSUE THREAD

**Issue by W2N-git** [aryaxt/OCMapper#26]
Should I always use "sharedInstance" instead of creating new instance of ObjectMapper?

**Comment by aryaxt** [comment]
shared instance is used in NSObject and NSDictionary categories, so if you don't want to use it you don't have to, but then you won't be able to use the helper categories.

https://github.com/aryaxt/OCMapper/tree/master/OCMapper/Source/Categories
