### ISSUE TITLE
Array of dates

### ISSUE THREAD

**Issue by W2N-git** [aryaxt/OCMapper#27]
I need array on NSDate, like this

@objc public class User: NSObject {
    var dates: [NSDate]?
}

And in JSON
{
    "dates": [
                "11/12/13",
              ]
}

But providing property does not work.

 let propertyProvider = InCodeMappingProvider()
propertyProvider.mapFromDictionaryKey("dates", toPropertyKey: "dates", withObjectType: NSDate.self, forClass: User.self)

ObjectMapper still generates strings.

Should I use provider with transformer or there is other way to do what i want?

Works fine if I add to method 

- (id)objectFromSource:(id)source toInstanceOfClass:(Class)class;

condition

else if ([source isKindOfClass:[NSString class]] && class == [NSDate class] ){
        return [self dateFromString:source forProperty:nil andClass:NULL];
}

But it looks ugly)

**Comment by aryaxt** [comment]
Will look into this, but for now you can write a transformer
```
[mappingProvider mapFromDictionaryKey:@"dates" toPropertyKey:@"dates" forClass:[User class] withTransformer:^id(id currentNode, id parentNode) {
     return currentNode;
}];
```
