### ISSUE TITLE
Automatically convert between underscores and camelCase

### ISSUE THREAD

**Issue by poetmountain** [aryaxt/OCMapper#31]
I often have to interact with APIs that use underscores in their JSON responses (e.g. 'some_property'). This forces me to do a lot of manual mapping to convert to ObjC/Swift camel case properties (e.g. 'someProperty). It would be fantastic if OCMapper could automatically convert between the two.

**Comment by aryaxt** [comment]
I'll check it out, if it doesn't bring the performance down will add it. Otherwise you could simply write a category to NSDictionary that loops through all keys and changes them to camel case before passing it to OCMapper, should be quite easy and straight forward

**Comment by poetmountain** [comment]
That's definitely an option, but since the underscore syntax is pretty common in APIs it seemed worth adding to the library. Thanks for looking into it!

**Comment by aryaxt** [comment]
This is now available on 2.1

**Comment by poetmountain** [comment]
Works great. Thanks for adding it! 🍺
