### ISSUE TITLE
How to handle boolean properties?

### ISSUE THREAD

**Issue by maml** [aryaxt/OCMapper#35]
I have an object with a boolean property but it never gets set, it's always nil. How should I declare this property?

```
MyObject {
  var id: NSNumber?
  var userId: NSNumber?
  var state: String?
  var active: Bool?
}
```

**Comment by aryaxt** [comment]
Just like core data. Use nsnumber for the property. Then call boolValue to get its value as a Boolean. 
Also the class must inherit from nsobject not quite sure how it's working right now without it, 
look at the samples for more info

**Comment by maml** [comment]
Great, thx!

**Comment by qimu** [comment]
This is great, thank you for the fix!
