### ISSUE TITLE
Nested mapping of classes

### ISSUE THREAD

**Issue by sssuourabh** [aryaxt/OCMapper#37]
I have json which contains an array of other classes as well so how to do nested mapping between classes.
Example
@interface APIOrganization : NSObject

@property (nonatomic , strong) NSString *id;
@property (nonatomic , strong) NSString *name;
@property (nonatomic , strong) APIPhoto *rmcPhoto;
@property (nonatomic , strong) NSMutableArray *Service;
@property (nonatomic , strong) NSMutableArray *osd;
@end

Here the APIOrganization class i am using 

APIOrganization *ApiOrg = [[ObjectMapper sharedInstance] objectFromSource:orgDict toInstanceOfClass:[APIOrganization class]]; 
Service is array of class Service class
but i am not getting the array which contain Service

Please guide me its very urgent 
@interface APIService : NSObject
@property (nonatomic , strong) NSString *id;// Doubt

@property (nonatomic , strong) NSString *name;

@property (nonatomic , strong) NSString *descriptions;

@property (nonatomic , strong) NSString *updatedOn;

**Comment by aryaxt** [comment]
automatic mapping happens when dictionary key is the same as property name and the class name
```map "users" to property named "users" with type User```
or
```map "user" to property named "user" with type User```

Since you don't have consistent naming you need to write mapping:
```
InCodeMappingProvider *mappingProvider = [[InCodeMappingProvider alloc] init];

[mappingProvider mapFromDictionaryKey:@"WHATEVER_THE_KEY_IS" toPropertyKey:@"osd" withObjectType:APIService.class forClass:APIOrganization.class];
// Add any other mapping needed

[[ObjectMapper sharedInstance] setMappingProvider:mappingProvider];
```
