### ISSUE TITLE
Not Working in Swift 2.0

### ISSUE THREAD

**Issue by dhavalgolakiya** [aryaxt/OCMapper#38]
Hi I'm using OCMapper in swift 1.2 and it is working correctly. But migrating to swift 2.0, it gives nil object.

In My Object

```
public class Response: NSObject {
    
    var flag = false
    var message : String?
    var announcement : String?
    var data : User?
}

public class User : Object  {

    dynamic var id = ""
    dynamic var imgName = ""
    dynamic var imageUrl = ""
    dynamic var mobile = ""
    dynamic var firstName = ""
    dynamic var lastName = ""
    dynamic var email = ""
}
```

User is a Realm Object.  When I map object from dictionary

```
 let response = dictionary?.toClass(Response.self)
```
or

```
let user = ObjectMapper.sharedInstance().objectFromSource(dictionary, toInstanceOfClass: Response.self) as? Response
```

Response gives data = nil and mapping failed.
It is working in Swift 1.2 so any issue of OCMapper with Swift 2.0 or any update for it?

**Comment by aryaxt** [comment]
Will look into this today

**Comment by dhvlgolakiya** [comment]
Hi,
I'm using OCMapper- version 2.1
iOS 9 and Xcode 7

This is completely working in iOS 8.4 and Xcode 6.4. But getting issue in iOS 9 and Xcode 7.

**Comment by aryaxt** [comment]
Can you provide any sample code? I converted my project to swift 2.0 and running on xcode7 everything works as expected
