### ISSUE TITLE
Array of Custom objects

### ISSUE THREAD

**Issue by abduranjum** [aryaxt/OCMapper#45]
I have an array of treatments. The class name is ICATreatment. The mapper maps the array to dictionary correctly, but fails to map from dictionary to array.

**Comment by aryaxt** [comment]
I need more information. If the array is nested to another object and the property name doesn't match the class name you need to write mapping. There are samples covering all cases here:

https://github.com/aryaxt/OCMapper/blob/master/OCMapperTests/ObjectMapperTests.m

**Comment by abduranjum** [comment]
It maps ICATreatment if is a simple property, but fails if it is in an array.

**Comment by abduranjum** [comment]
I could not find this example in the readme file.
