### ISSUE TITLE
Alamofire extension for Alamofire 4.x

### ISSUE THREAD

**Issue by balazsgerlei** [aryaxt/OCMapper#59]
Hi!
I use OCMapper with Alamofire in my application (I would think it is quite a common use case), so like in my previous issue (#53), I would appreciate to see an Alamofire extension example in the README. I already updated my app to Swift 3 and thus Alamofire 4.x, and created the extension myself, so I would be happy to create a pull request to update the readme with both examples (for Alamofire 3.x and 4.x). Do you accept pull requests like this?

I will post my solution here soon for anyone to check.

**Comment by aryaxt** [comment]
Sorry too late to this, but It's quite simple to add an extension on top of alamofire in any project, I prefer not to add a dependency to it in the pod

**Comment by balazsgerlei** [comment]
@aryaxt I said nothing about adding the extension to the library, I asked to add the extension example to the README. Currently it has the extension example for Alamofire 2.x, but I asked you to include one for Alamofire 3.x (#53) and Alamofire 4.x, that's all. In the other issue for 3.x I even added an example I cam up with and you also wrote another one.

I no longer need these additions, as I already implemented them, but it may be useful for newcommers, as currently they only see a quite deprecated example.
