### ISSUE TITLE
Support for custom factory methods

### ISSUE THREAD

**Issue by laenger** [aryaxt/OCMapper#9]
In this particular situation I need to map an array to a nested object.
```
From
{p:[3,4]}
To
X
_p
__a
__b
```
The Jackson Java library supports custom factory methods, e.g., through the `@JsonCreator` annotation, that allow me to realize such a mapping in the following way. Jackson then searches for a suitable factory method whenever it has to map `int[]` to `P`. Support for some sort of factory methods would be a powerful feature.
```java
public class X {
    @JsonProperty("p")
    private P p;
}

public class P {
    private int a;
    private int b;

    public P(int a, int b) {
        this.a= a;
        this.b= b;
    }

    @JsonCreator
    public static P fromValue(int[] array) {
        return new P(array[0], array[1]);
    }
}
```

**Comment by aryaxt** [comment]
Good Idea, will add this as a feature. Can you confirm that below is the type of feature you were talking about?

```
[mappingProvider mapFromKey:@"country" toProperty:@"country" withTransformer:^(id countryString) {
    Country *country = [[Country alloc] init];
    return country;
]};
```

**Comment by laenger** [comment]
The difference between the Java example and your suggestion is that you are specifiying the mapping configuration through the parent object (`User` in this case) instead of the object itself (`Country`). Therefore one would have to repeat the configuration for other Objects with a country property (say, `Business`). However, I believe that your approach is consistent with the existing mapping provider API and I am not going to complain about this solution :)

**Comment by laenger** [comment]
oh and will you pass in the primitive type (int, array, string, ...) into the transformer or only the raw string? or will users be able to change the header of the transformer function according to what the json is expected to look like? e.g:

```
[mappingProvider mapFromKey:@"country" toProperty:@"country" forClass:[User class] withTransformer:^(NSArray* a) {
    Country *country = [[Country alloc] initWithX:a[0] andY:a[1]];
    return country;
]};
```

**Comment by aryaxt** [comment]
No transformer would take whatever is in the dictionary for the given key, so it could be anything (string, number, array, dictionary)

**Comment by aryaxt** [comment]
Feature is implemented in a separate branch and docs are updated. Will do more testing and merge into master
